name: Scan with Detekt

on: [push, pull_request]

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

#    - name: Setup Gradle
#      uses: gradle/gradle-build-action@v2

    - name: Run Detekt
      run: ./gradlew detekt
